### ISSUE TITLE
Error while creating MPRA object

### ISSUE THREAD

**Issue by SebastienNin** [YosefLab/MPRAnalyze#12]
Hi,
I'm trying to run MPRAnalyze on the results of the of the MPRAflow workflow found [here](https://mpraflow.readthedocs.io/en/latest/count_example1.html). I ran it using the --mpranalyze option to get the necessary files for MPRAnalyze.

My problem comes when I try to load my counts and annotations into an MPRA object.

I run the following:

library(MPRAnalyze)
ce.dnaCounts <- as.data.frame(read.delim("HEPG2/dna_counts.tsv", row.names = 1))
ce.rnaCounts <- as.data.frame(read.delim("HEPG2/rna_counts.tsv", row.names = 1))
ce.dnaAnnot <- as.data.frame(read.delim("HEPG2/dna_annot.tsv", row.names = 1))
ce.rnaAnnot <- as.data.frame(read.delim("HEPG2/rna_annot.tsv", row.names = 1))

obj <- MpraObject(dnaCounts = ce.dnaCounts, rnaCounts = ce.rnaCounts, 
                  dnaAnnot = ce.dnaAnnot, rnaAnnot = ce.rnaAnnot)

I got the following error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘MpraObject’ for signature ‘"data.frame"’

I can't find enough information on the package to resolve this error. can you please help me resolving it?

Regards,
Sebastien

**Comment by talashuach** [comment]
Hi Sebastian,

The error is because the function expects the count matrices to be matrices, not data.frames.

Try:
```
ce.dnaCounts <- as.matrix(read.delim("HEPG2/dna_counts.tsv", row.names = 1))
ce.rnaCounts <- as.matrix(read.delim("HEPG2/rna_counts.tsv", row.names = 1))
ce.dnaAnnot <- as.data.frame(read.delim("HEPG2/dna_annot.tsv", row.names = 1))
ce.rnaAnnot <- as.data.frame(read.delim("HEPG2/rna_annot.tsv", row.names = 1))

**Comment by SebastienNin** [comment]
Hi @talashuach 
thank you for your fast answer. It works! I close this issue

Regards,
Sebastien
