### ISSUE TITLE
Error in MpraObject

### ISSUE THREAD

**Issue by visze** [YosefLab/MPRAnalyze#7]
Hey Tal,

I just checked out you latest version and try to rerun it on my data. But I think there is a problem with the `dnaCounts` in the `MpraObject`. When creating a new object I get the error;

```R
obj <- MpraObject(dnaCounts,rnaCounts,  dnaAnnot = grid, rnaAnnot = grid)
Error in rownames(objects@dnaCounts) :
  trying to get slot "dnaCounts" from an object of a basic class ("function") with no slots
```

You get also the same error if you check out the latest version on github and try to build it by yourself via `R CMD build `. Here creating the object in `vignette.Rmd` fails:

```
R CMD build .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘MPRAnalyze’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 43-47 (vignette.Rmd)
Error: processing vignette 'vignette.Rmd' failed with diagnostics:
trying to get slot "dnaCounts" from an object of a basic class ("function") with no slots
Execution halted
```

Any suggestions?

Thx,
Max

**Comment by talashuach** [comment]
Hi Max,

sorry about that, it was an impressively dumb typo that I somehow pushed. It's now fixed and should run fine (make sure you run version 0.99.3).

Please let me know if you have any more issues with it!

Thanks,
Tal

**Comment by visze** [comment]
Thanks!

Works fine now!
