### ISSUE TITLE
Error issue: analyzeComparative

### ISSUE THREAD

**Issue by dmontielg** [YosefLab/MPRAnalyze#9]
Hi, 

I followed the tutorial from Bioconductor 
https://bioconductor.org/packages/release/bioc/vignettes/MPRAnalyze/inst/doc/vignette.html
then, I processed and generated the tables required using mine data. But I am getting an error in the _analyzeComparative_ function. 
**Fitting controls-based background model...
Error in log.d.est + rep((rdesign.mat %*% theta[-1]) + log.rdepth, NCOL(log.d.est)) : 
  non-conformable arrays**

I am doing the analysis for allelic comparisons. So, instead of condition as you have in the tutorial, I changed it for allele A and B. 

Thanks in advanced,

Diego

**Comment by talashuach** [comment]
Hi Diego,

Could you please email me a small sample of your data (feel free to remove identifying information or annotations) and the code that produces this error?
Send to tal_ashuach@berkeley.edu

Thanks

**Comment by dmontielg** [comment]
Thanks a lot for your reply.
